Repository IgniteUI/igniteui-react-examples, pull requests merged in 2024-09, with the labels that each got.

#629 Add Banner samples
  samples/notifications/banner/banner-advanced-sample/.eslintrc.js
  samples/notifications/banner/banner-advanced-sample/README.md
  samples/notifications/banner/banner-advanced-sample/package.json
  samples/notifications/banner/banner-advanced-sample/public/index.html
  samples/notifications/banner/banner-advanced-sample/sandbox.config.json
  samples/notifications/banner/banner-advanced-sample/src/BannerAdvancedSample.css
  samples/notifications/banner/banner-advanced-sample/src/index.css
  samples/notifications/banner/banner-advanced-sample/src/index.tsx
  samples/notifications/banner/banner-advanced-sample/src/react-app-env.d.ts
  samples/notifications/banner/banner-advanced-sample/tsconfig.json
  samples/notifications/banner/banner-sample-1/.eslintrc.js
  samples/notifications/banner/banner-sample-1/README.md
  samples/notifications/banner/banner-sample-1/package.json
  samples/notifications/banner/banner-sample-1/public/index.html
  samples/notifications/banner/banner-sample-1/sandbox.config.json
  samples/notifications/banner/banner-sample-1/src/BannerSample1.css
  samples/notifications/banner/banner-sample-1/src/index.css
  samples/notifications/banner/banner-sample-1/src/index.tsx
  samples/notifications/banner/banner-sample-1/src/react-app-env.d.ts
  samples/notifications/banner/banner-sample-1/tsconfig.json
  samples/notifications/banner/banner-sample-2/.eslintrc.js
  samples/notifications/banner/banner-sample-2/README.md
  samples/notifications/banner/banner-sample-2/package.json
  samples/notifications/banner/banner-sample-2/public/index.html
  samples/notifications/banner/banner-sample-2/sandbox.config.json
  samples/notifications/banner/banner-sample-2/src/BannerSample2.css
  samples/notifications/banner/banner-sample-2/src/index.css
  samples/notifications/banner/banner-sample-2/src/index.tsx
  samples/notifications/banner/banner-sample-2/src/react-app-env.d.ts
  samples/notifications/banner/banner-sample-2/tsconfig.json
  samples/notifications/banner/banner-styling/.eslintrc.js
  samples/notifications/banner/banner-styling/README.md
  samples/notifications/banner/banner-styling/package.json
  samples/notifications/banner/banner-styling/public/index.html
  samples/notifications/banner/banner-styling/sandbox.config.json
  samples/notifications/banner/banner-styling/src/BannerStyling.css
  samples/notifications/banner/banner-styling/src/index.css
  samples/notifications/banner/banner-styling/src/index.tsx
  samples/notifications/banner/banner-styling/src/react-app-env.d.ts
  samples/notifications/banner/banner-styling/tsconfig.json
Labels: status: verified

#620 Add grid custom icons change sample.
  samples/grids/grid/change-icons-custom/.eslintrc.js
  samples/grids/grid/change-icons-custom/ReadMe.md
  samples/grids/grid/change-icons-custom/package.json
  samples/grids/grid/change-icons-custom/public/index.html
  samples/grids/grid/change-icons-custom/sandbox.config.json
  samples/grids/grid/change-icons-custom/src/NwindData.ts
  samples/grids/grid/change-icons-custom/src/icons.ts
  samples/grids/grid/change-icons-custom/src/index.css
  samples/grids/grid/change-icons-custom/src/index.tsx
  samples/grids/grid/change-icons-custom/src/react-app-env.d.ts
  samples/grids/grid/change-icons-custom/tsconfig.json
Labels: status: verified

#617 Update index.tsx
  samples/gauges/radial-gauge/labels/src/index.tsx
Labels: status: in-review

#640 fix(drag): Fix issue with drag&drop custom samples.
  samples/grids/grid/row-drag-base/src/index.tsx
  samples/grids/hierarchical-grid/row-drag-base/src/index.tsx
  samples/grids/tree-grid/row-drag-base/src/index.tsx
Labels: status: verified

#614 Add state persistence samples for Tree and Hierarchical grids
  samples/grids/grid/state-persistence-main/src/index.tsx
  samples/grids/hierarchical-grid/state-persistence-about/.eslintrc.js
  samples/grids/hierarchical-grid/state-persistence-about/ReadMe.md
  samples/grids/hierarchical-grid/state-persistence-about/package.json
  samples/grids/hierarchical-grid/state-persistence-about/public/index.html
  samples/grids/hierarchical-grid/state-persistence-about/sandbox.config.json
  samples/grids/hierarchical-grid/state-persistence-about/src/index.css
  samples/grids/hierarchical-grid/state-persistence-about/src/index.tsx
  samples/grids/hierarchical-grid/state-persistence-about/src/react-app-env.d.ts
  samples/grids/hierarchical-grid/state-persistence-about/tsconfig.json
  samples/grids/hierarchical-grid/state-persistence-main/.eslintrc.js
  samples/grids/hierarchical-grid/state-persistence-main/ReadMe.md
  samples/grids/hierarchical-grid/state-persistence-main/package.json
  samples/grids/hierarchical-grid/state-persistence-main/public/index.html
  samples/grids/hierarchical-grid/state-persistence-main/sandbox.config.json
  samples/grids/hierarchical-grid/state-persistence-main/src/SingersData.json
  samples/grids/hierarchical-grid/state-persistence-main/src/index.css
  samples/grids/hierarchical-grid/state-persistence-main/src/index.tsx
  samples/grids/hierarchical-grid/state-persistence-main/src/react-app-env.d.ts
  samples/grids/hierarchical-grid/state-persistence-main/tsconfig.json
  samples/grids/pivot-grid/state-persistence-about/.eslintrc.js
  samples/grids/pivot-grid/state-persistence-about/ReadMe.md
  samples/grids/pivot-grid/state-persistence-about/package.json
  samples/grids/pivot-grid/state-persistence-about/public/index.html
  samples/grids/pivot-grid/state-persistence-about/sandbox.config.json
  samples/grids/pivot-grid/state-persistence-about/src/index.css
  samples/grids/pivot-grid/state-persistence-about/src/index.tsx
  samples/grids/pivot-grid/state-persistence-about/src/react-app-env.d.ts
  samples/grids/pivot-grid/state-persistence-about/tsconfig.json
  samples/grids/pivot-grid/state-persistence-main/.eslintrc.js
  samples/grids/pivot-grid/state-persistence-main/ReadMe.md
  samples/grids/pivot-grid/state-persistence-main/package.json
  samples/grids/pivot-grid/state-persistence-main/public/index.html
  samples/grids/pivot-grid/state-persistence-main/sandbox.config.json
  samples/grids/pivot-grid/state-persistence-main/src/PivotDataFlat.ts
  samples/grids/pivot-grid/state-persistence-main/src/index.css
  samples/grids/pivot-grid/state-persistence-main/src/index.tsx
  samples/grids/pivot-grid/state-persistence-main/src/react-app-env.d.ts
  samples/grids/pivot-grid/state-persistence-main/tsconfig.json
  samples/grids/tree-grid/state-persistence-about/.eslintrc.js
  samples/grids/tree-grid/state-persistence-about/ReadMe.md
  samples/grids/tree-grid/state-persistence-about/package.json
  samples/grids/tree-grid/state-persistence-about/public/index.html
  samples/grids/tree-grid/state-persistence-about/sandbox.config.json
  samples/grids/tree-grid/state-persistence-about/src/index.css
  samples/grids/tree-grid/state-persistence-about/src/index.tsx
  samples/grids/tree-grid/state-persistence-about/src/react-app-env.d.ts
  samples/grids/tree-grid/state-persistence-about/tsconfig.json
  samples/grids/tree-grid/state-persistence-main/.eslintrc.js
  samples/grids/tree-grid/state-persistence-main/ReadMe.md
  samples/grids/tree-grid/state-persistence-main/package.json
  samples/grids/tree-grid/state-persistence-main/public/index.html
  samples/grids/tree-grid/state-persistence-main/sandbox.config.json
  samples/grids/tree-grid/state-persistence-main/src/EmployeesNestedData.ts
  samples/grids/tree-grid/state-persistence-main/src/index.css
  samples/grids/tree-grid/state-persistence-main/src/index.tsx
  samples/grids/tree-grid/state-persistence-main/src/react-app-env.d.ts
  samples/grids/tree-grid/state-persistence-main/tsconfig.json
Labels: status: verified

#642 Fix issue with custom context menu sample
  samples/grids/grid/custom-context-menu/src/index.tsx
Labels: status: verified

#650 Adding Divider Samples
  samples/layouts/divider/base/.eslintrc.js
  samples/layouts/divider/base/README.md
  samples/layouts/divider/base/package.json
  samples/layouts/divider/base/public/index.html
  samples/layouts/divider/base/sandbox.config.json
  samples/layouts/divider/base/src/index.css
  samples/layouts/divider/base/src/index.tsx
  samples/layouts/divider/base/src/react-app-env.d.ts
  samples/layouts/divider/base/tsconfig.json
  samples/layouts/divider/dashed/.eslintrc.js
  samples/layouts/divider/dashed/README.md
  samples/layouts/divider/dashed/package.json
  samples/layouts/divider/dashed/public/index.html
  samples/layouts/divider/dashed/sandbox.config.json
  samples/layouts/divider/dashed/src/index.css
  samples/layouts/divider/dashed/src/index.tsx
  samples/layouts/divider/dashed/src/react-app-env.d.ts
  samples/layouts/divider/dashed/tsconfig.json
  samples/layouts/divider/middle/.eslintrc.js
  samples/layouts/divider/middle/README.md
  samples/layouts/divider/middle/package.json
  samples/layouts/divider/middle/public/index.html
  samples/layouts/divider/middle/sandbox.config.json
  samples/layouts/divider/middle/src/index.css
  samples/layouts/divider/middle/src/index.tsx
  samples/layouts/divider/middle/src/react-app-env.d.ts
  samples/layouts/divider/middle/tsconfig.json
  samples/layouts/divider/select/.eslintrc.js
  samples/layouts/divider/select/README.md
  samples/layouts/divider/select/package.json
  samples/layouts/divider/select/public/index.html
  samples/layouts/divider/select/sandbox.config.json
  samples/layouts/divider/select/src/index.css
  samples/layouts/divider/select/src/index.tsx
  samples/layouts/divider/select/src/react-app-env.d.ts
  samples/layouts/divider/select/tsconfig.json
  samples/layouts/divider/vertical/.eslintrc.js
  samples/layouts/divider/vertical/README.md
  samples/layouts/divider/vertical/package.json
  samples/layouts/divider/vertical/public/index.html
  samples/layouts/divider/vertical/sandbox.config.json
  samples/layouts/divider/vertical/src/index.css
  samples/layouts/divider/vertical/src/index.tsx
  samples/layouts/divider/vertical/src/react-app-env.d.ts
  samples/layouts/divider/vertical/tsconfig.json
Labels: status: in-review, status: verified
